spring:
  application:
    name: flowpay-atendimento
  datasource:
    url: jdbc:postgresql://localhost:5432/flowpay
    username: flowpay
    password: flowpay
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
#logging:
#  level:
#    com.flowpay.atendimento: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE

logging:
  level:
    com.flowpay.atendimento: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: OFF